//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO.Seguridad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguridadContainer : DbContext
    {
        public SeguridadContainer()
            : base("name=SeguridadContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formulario> FormularioSet { get; set; }
        public virtual DbSet<Permiso> PermisoSet { get; set; }
        public virtual DbSet<Perfil> PerfilSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
    }
}
