//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public long dni { get; set; }
        public string apellido { get; set; }
        public string mail { get; set; }
        public string contraseña { get; set; }
        public int empresa_id { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
